### ISSUE TITLE
section attribute not allowed for 'Pchr'

### ISSUE THREAD

**Issue by redlegoman** [adafruit/Adafruit_ESP8266#8]
When I try to compile the "webclient" example, I get the following error:

In file included from espneotest.ino:1:0:
/Volumes/MacHDD/Dropbox/Dropbox/programming/arduino/libraries/Adafruit_ESP8266/Adafruit_ESP8266.h:28:35: error: section attribute not allowed for 'Pchr'
 typedef const PROGMEM char        Pchr; // Ditto, kindasorta
                                   ^
Error compiling.

**Comment by tdicola** [comment]
Oh I think you want to open this on the main ESP8266 Arduino github repo--this one is just a fork we made to send a few small pull requests.  Their repo is here: https://github.com/esp8266/Arduino  Make sure to get their latest code and check if it repros there as they move a lot faster than our fork keeps up and might have already caught & fixed it.  Thanks!

**Comment by whogarden** [comment]
Hello,
I have the same pb with the "send_email_smtp" from Adafruit and the last libraries (to day updated).
What can I do, please?

**Comment by drdavel** [comment]
I have the same issue, een after installing the github repo.

**Comment by adityathakekar** [comment]
section attribute not allowed for 'Pchr'

 typedef const PROGMEM char        Pchr; // Ditto, kindasorta
same error again and again

**Comment by debrucer** [comment]
same... it wasn't in the new repos

**Comment by tuanhuy127** [comment]
Please chose other board option in Tool\board: select  Arduino\GenuinoUno! then complie it...

**Comment by k-byte-rgb** [comment]
i have this error also. With arduino uno and it does not have the fault, but he has to compile before uploading on the board you want it to upload to.
